# Standalone file: do not edit by hand
# Generated by: pkgtools from @unit tags
# ----------------------------------------------------------------------
library(rsurvstat)

# unit test start: date_from_iso ----

test_that("date_from_iso unit test", {

  # Automatically generated test case from roxygen @unit tag
  # Do not edit here - follow the link to the source file.
  # or navigate to topic with <F2>
  F2 = date_from_iso
  

  years = c(2001, 2001, 2004, 2028)
  weeks = c(1, 52, 53, 52)
  correct = c("2001-01-01", "2001-12-24", "2004-12-27", "2028-12-25") %>% as.Date()
  # format(correct, "%Y-W%V")
  
  testthat::expect_equal(
    date_from_iso(years, weeks),
    correct
  )

  # generates a failure if the overall test is failing with a link to the 
  # source of the unit test:
  testthat::expect(rlang::caller_env(n = 2)$ok,
    failure_message = "Source link for failing @unit test.",
    srcref = srcref(srcfile("../../R/survstat-loader.R"), c(864, 1, 864+1, 1))
  )
})

# unit test end: date_from_iso ----
# end of unit tests ----
